on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: "Test on ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    steps:
    - name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: 15
    - name: Clone root repository
      uses: actions/checkout@v2
      with:
        repository: sandpolis/sandpolis
    - name: Checkout submodules
      run: |
        git submodule update --init --remote --merge com.sandpolis.client.ascetic
    - name: Run tests
      run: |
        ./gradlew :com.sandpolis.client.ascetic:test

  push:
    name: Push image to Docker Hub
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
    - name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: 15
    - name: Clone root repository
      uses: actions/checkout@v2
      with:
        repository: sandpolis/sandpolis
    - name: Checkout submodules
      run: |
        git submodule update --init --remote --merge com.sandpolis.client.ascetic
    - name: DockerHub login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: DockerHub push
      uses: docker/build-push-action@v2
      with:
        context: .
        platforms: linux/amd64,linux/arm64,linux/386
        push: true
        tags: sandpolis/terminal-client:latest
